# Generated by Django 6.0.4 on 2026-04-25 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedfilter',
            options={'ordering': ['-is_pinned', '-updated_at']},
        ),
        migrations.AddField(
            model_name='savedfilter',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
