# Generated by Django 6.0.4 on 2026-04-23 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternativeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_difference', models.DecimalField(decimal_places=2, max_digits=10)),
                ('alternative_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternative_product_matches', to='products.product')),
                ('main_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_product_alternatives', to='products.product')),
            ],
            options={
                'ordering': ['-price_difference', '-similarity_score'],
                'constraints': [models.UniqueConstraint(fields=('main_product', 'alternative_product'), name='unique_alternative_pair')],
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_url', models.URLField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='products.product')),
            ],
            options={
                'ordering': ['price'],
                'constraints': [models.UniqueConstraint(fields=('product', 'platform'), name='unique_product_platform_price')],
            },
        ),
    ]
