# Generated by Django 6.0.4 on 2026-04-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productnews'),
    ]

    operations = [
        migrations.AddField(
            model_name='productnews',
            name='topic',
            field=models.SlugField(choices=[('launches', 'Launches'), ('deals', 'Deals'), ('reviews', 'Reviews'), ('price-drops', 'Price Drops'), ('guides', 'Guides'), ('accessories', 'Accessories')], default='launches', max_length=64),
        ),
    ]
