# Generated by Django 6.0.4 on 2026-04-30 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productnews_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productnews',
            name='topic',
        ),
        migrations.AddField(
            model_name='productnews',
            name='news_category',
            field=models.CharField(choices=[('launches', 'Product Launches'), ('pricing', 'Price Updates'), ('deals', 'Hot Deals'), ('tech', 'Technology & Features'), ('reviews', 'Reviews & Analysis'), ('general', 'General News')], db_index=True, default='general', max_length=20),
        ),
    ]
