# Generated by Django 5.2.12 on 2026-05-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_productnews_topic_productnews_news_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productnews',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload news image (recommended: 800x600px or wider)', upload_to='news/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='productnews',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional: External image URL as fallback'),
        ),
    ]
