# Generated by Django 5.2.12 on 2026-05-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productnews_image_alter_productnews_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/uploaded/%Y/%m/%d/'),
        ),
    ]
