# Generated by Django 6.0.4 on 2026-05-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_source',
            field=models.CharField(default='manual', max_length=50),
        ),
    ]
